title: Michael Dymock
email: michael.dymock@thekids.org.au
description: > # this means to ignore newlines until "baseurl:"
  Biostatistician at The Kids Research Institute Australia and
  PhD student at The University of Western Australia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  michaeldymock25
twitter_username:  mdymock25

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - code
  - Gemfile
  - Gemfile.lock
